### ISSUE TITLE
Vulnerability and license scanning - Java

### ISSUE THREAD

**Issue by martin-traverse** [Accenture/trac#74]
These scans  will cover the core platform services:

- Automated vulnerability scanning
- License scanning, to check for license conflicts in dependencies

Both scans to run out of CI and publish results as build artifacts. Probably it is sufficient to run on PR, merge and tag events.

(The same scanning should cover the Java/Scala model runtime in future).

**Comment by maoo** [comment]
Answering to myself re. JS and Python validations... see #75 and #76

@martin-traverse - I reviewed reports on https://github.com/martin-traverse/trac/tree/feature/java_compliance/dev . LGTM, thank you!

**Comment by martin-traverse** [comment]
That's great, thanks @maoo, I will prepare PRs for the other two languages.
