### ISSUE TITLE
Vulnerability and license scanning - Python

### ISSUE THREAD

**Issue by martin-traverse** [Accenture/trac#75]
These scans will relate to the Python model runtime:

- Automated vulnerability scanning
- License scanning, to check for license conflicts in dependencies

Both scans to run out of CI and publish results as build artifacts. Probably it is sufficient to run on PR, merge and tag events.

**Comment by martin-traverse** [comment]
Hi @maoo , I have put in an implementation of compliance reporting for Python, it uses "safety", which I believe is the same underlying technology that Poetry uses for compliance validation.

I have merged the initial implementation and published a beta release of TRAC, the release has the compliance outputs attached as an artifact, so you can see what the output would look like:

https://github.com/Accenture/trac/releases/tag/v0.3.0-beta2

CI is set up to publish compliance reports with every release. They are also produced (as build artifacts only) for every PR and merge to main, which will fail PR and merge builds if there are any compliance failures.

If you want to look at the PR for the Python piece in isolation it is here: https://github.com/Accenture/trac/pull/89

If there are compliance requirements from FINOS that are still not met then please let me know and I'll do the work to include them before the 0.3 release. Although TRAC will not be under the FINOS banner in time for the 0.3 release, if we can get the release in line with the FINOS compliance standards I think that would be a good thing!

**Comment by maoo** [comment]
I checked the report, and everything is in place. Thanks so much @martin-traverse !

**Comment by martin-traverse** [comment]
Great, closing the compliance issues.
