### ISSUE TITLE
Vulnerability and license scanning - JavaScript

### ISSUE THREAD

**Issue by martin-traverse** [Accenture/trac#76]
These scans will relate to the web API package:

- Automated vulnerability scanning
- License scanning, to check for license conflicts in dependencies

Both scans to run out of CI and publish results as build artifacts. Probably it is sufficient to run on PR, merge and tag events.

**Comment by martin-traverse** [comment]
Hi - I have linked the PR for JavaScript compliance. I found node-license-validator introduced dependencies with security advisories, so I have used NPM license checker instead (https://www.npmjs.com/package/license-checker-rseidelsohn). Functionality is almost identical. NPM audit output is included as suggested. I also found the OWASP dependency checker tool works across multiple languages, including JavaScript with NPM dependencies. I have included that too so there are three compliance artefacts produced for the web API.

Sample outputs are on the compliance workflow run for the  PR: https://github.com/Accenture/trac/actions/runs/1527174883

**Comment by maoo** [comment]
Thanks @martin-traverse , great stuff! I see that compliance reports artifacts are uploaded (see https://github.com/Accenture/trac/runs/4385501116?check_suite_focus=true#step:7:14 ), but I couldn't find a link to it. Could you please point me to the report? TY!

**Comment by martin-traverse** [comment]
Hi @maoo - Try this one?
https://github.com/Accenture/trac/actions/runs/1527174883

Before I finish the compliance work I'll add a task that includes the output bundle with release artefacts when a release is published.

**Comment by maoo** [comment]
Still can't find a report. I can see that build is successful in the `License check` step (see https://github.com/Accenture/trac/runs/4385501116?check_suite_focus=true#step:6:81 ). Does that imply that it's all good? Would be interesting to try adding a "bad" dependency and see how it fails.

**Comment by martin-traverse** [comment]
Ah - it looks like you need some permissions on the repo in order to be able to get the artefacts out of the workflow run. If I look at the run without logging in, I can see the "compliance-reports" artefact on the summary page, but I can't download it. I don't have permissions to give you access, it would need to be an Accenture org admin who can do that.

I will send you a copy of the reports to review. Also, for public visibility, I will make every release job attach a copy of the compliance report outputs as a release artefact, which will then be visible to everyone.
